<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mental Health and Standardized Test Scores – Aaron Kim</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Mental Health and Standardized Test Scores – Aaron Kim">
<meta property="og:description" content="">
<meta property="og:site_name" content="Aaron Kim">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Aaron Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./FinalProject.html" aria-current="page"> 
<span class="menu-text">Mental Health and Standardized Test Scores</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mental Health and Standardized Test Scores</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="motivation-and-context" class="level2">
<h2 class="anchored" data-anchor-id="motivation-and-context">Motivation and Context</h2>
<p>I spent a significant amount of time in high school engaged in seriously rigorous coursework, such as AP classes, which somewhat took a toll on my mental well-being. More than a few times during this period of my life, I said to myself “It would really be nice if there was someone who I could talk to about all this.” Though thankfully I’ve managed to achieve a much healthier balance in my life since entering college, I still retain an interest in the mental health of students, which is why I was motivated to center my project on these ideas.</p>
<p>It is commonly said that America today is in a mental health crisis - the CDC states that a staggering one in five Americans suffer from anxiety or depression, with the youth being even more severely effected [https://www.cdc.gov/mental-health/about/what-cdc-is-doing.html]. With the increase in the severity in this crisis has apparently come an increase in awareness and resources available to help meet it, however. In this project I intend to only cover mental health issues and educational results that are common and familiar to the average person (i.e., depression and anxiety for mental health, and standardized test scores for educational results). Thus, no additional context is required for a general audience to understand the concepts at play.</p>
</section>
<section id="main-objective" class="level2">
<h2 class="anchored" data-anchor-id="main-objective">Main Objective</h2>
<p>The objective of this project is to determine whether an association exists between the mental well-being of high school students and their performance on standardized tests.</p>
</section>
<section id="packages-used-in-this-analysis" class="level2">
<h2 class="anchored" data-anchor-id="packages-used-in-this-analysis">Packages Used In This Analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(recipes)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Package</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://github.com/jennybc/here_here">here</a></td>
<td>to easily load and save data</td>
</tr>
<tr class="even">
<td><a href="https://readr.tidyverse.org/">readr</a></td>
<td>to import the CSV file data</td>
</tr>
<tr class="odd">
<td><a href="https://dplyr.tidyverse.org/">dplyr</a></td>
<td>to massage and summarize data</td>
</tr>
<tr class="even">
<td><a href="https://rsample.tidymodels.org/">rsample</a></td>
<td>to split data into training and test sets</td>
</tr>
<tr class="odd">
<td><a href="https://ggplot2.tidyverse.org/">ggplot2</a></td>
<td>to create nice-looking and informative graphs</td>
</tr>
<tr class="even">
<td><a href="https://readxl.tidyverse.org/">readxl</a></td>
<td>to load the data</td>
</tr>
<tr class="odd">
<td><a href="https://github.com/tidymodels/recipes">recipes</a></td>
<td>for linear imputation</td>
</tr>
<tr class="even">
<td><a href="https://dplyr.tidyverse.org/">dplyr</a></td>
<td>for linear imputation</td>
</tr>
</tbody>
</table>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<p>SAT data was gathered from this site: [[https://nces.ed.gov/programs/digest/d21/tables/dt21_226.40.asp]], while ACT data was gathered from this site: [[https://www.act.org/content/dam/act/unsecured/documents/2021/2021-Average-ACT-Scores-by-State.pdf]]. The information on standardized test performances comes from the National Center for Education Statistics, a federal statistics agency whose entire job it is to collect data related to educational results. They state that their data comes from College Board, the organization that runs the SAT. The data about the ACT comes from act.org itself.</p>
<p>To supplement this information, pre-COVID data about the SAT Scores by state were gathered from Kaggle: [[https://www.kaggle.com/datasets/mexwell/us-school-scores]].</p>
<p>For the mental health: [[https://www.cdc.gov/yrbs/results/index.html]], then follow to “Youth Online High School Results” and “Unintentional Injuries and Violence”. The CDC is the Center for Disease Control, an American public health institution. As their stated mission is to protect and improve public health in the country, mental illnesses fall under their jurisdiction, which is why data on mental health was collected by the organization. From the CDC’s “Youth Risk Behavior Surveillance System” (YRBSS), I initially began using the proportion of high school students in 2021 who “felt sad or hopeless” in order to represent overall mental well-being of students. The “Youth Online”’s main page says that their data is collected from the Global School-Based Student Health Survey (GSHS), a survey organized by the World Health Organization to “provide accurate data on health behaviors and protective factors among students” [[https://www.who.int/teams/noncommunicable-diseases/surveillance/systems-tools/global-school-based-student-health-survey/methodology]].</p>
<p>In addition to this, I am also using other statistics gathered by the YRBSS. These include the percentage of surveyed high schoolers who actually attempted suicide, the percentage who were not getting 8 or more hours of sleep, and the percentage who reported that they were binge drinking. These factors were selected out of the many different YRBSS surveys due to all of them commonly being commonly associated with poor mental health. I expect for the percentage of students who answered “yes” to these questions to increase alongside the percentage of students who report feeling sad or hopeless.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>test_scores2021 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/aaronskim/Documents/Math 437/Data/standardized_test_scores.xlsx"</span>) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>sad_percent2021 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/aaronskim/Documents/Math 437/Data/felt_sad_2021.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>attempt_suicide2021 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/aaronskim/Documents/Math 437/Data/AttemptedSuicide2021.xlsx"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>binge_drinking2021 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/aaronskim/Documents/Math 437/Data/BingeDrinking2021.xlsx"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sleeping_enough2021 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/aaronskim/Documents/Math 437/Data/Sleeping8Hours2021.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data2021 <span class="ot">&lt;-</span> test_scores2021[<span class="dv">4</span><span class="sc">:</span><span class="dv">54</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data2021[, <span class="dv">4</span>] <span class="ot">&lt;-</span> sad_percent2021[<span class="dv">5</span><span class="sc">:</span><span class="dv">55</span>, <span class="dv">2</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data2021)[<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="st">"Sadness"</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>data2021[, <span class="dv">5</span>] <span class="ot">&lt;-</span> sleeping_enough2021[<span class="dv">5</span><span class="sc">:</span><span class="dv">55</span>, <span class="dv">2</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data2021)[<span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="st">"Not_Sleeping_Enough"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>data2021[, <span class="dv">6</span>] <span class="ot">&lt;-</span> attempt_suicide2021[<span class="dv">5</span><span class="sc">:</span><span class="dv">55</span>, <span class="dv">2</span>]</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data2021)[<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="st">"Attempted_Suicide"</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>data2021[, <span class="dv">7</span>] <span class="ot">&lt;-</span> sad_percent2021[<span class="dv">5</span><span class="sc">:</span><span class="dv">55</span>, <span class="dv">2</span>]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data2021)[<span class="dv">7</span>] <span class="ot">&lt;-</span> <span class="st">"Binge_Drinkers"</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>data2021<span class="sc">$</span>Sadness <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data2021<span class="sc">$</span>Sadness)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>data2021<span class="sc">$</span>Not_Sleeping_Enough <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data2021<span class="sc">$</span>Not_Sleeping_Enough)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>data2021<span class="sc">$</span>Attempted_Suicide <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data2021<span class="sc">$</span>Attempted_Suicide)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>data2021<span class="sc">$</span>Binge_Drinkers <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(data2021<span class="sc">$</span>Binge_Drinkers)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>data2021</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51 × 7
   State                 SAT   ACT Sadness Not_Sleeping_Enough Attempted_Suicide
   &lt;chr&gt;               &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;             &lt;dbl&gt;
 1 Alabama              1159  18.7    36.9                77.4              NA  
 2 Alaska               1119  20.6    NA                  NA                NA  
 3 Arizona              1181  19.8    NA                  79.3              10.4
 4 Arkansas             1194  19      42.9                77.8              10.4
 5 California           1057  26.1    NA                  NA                NA  
 6 Colorado             1072  23.6    41.7                75.6              11.9
 7 Connecticut          1072  27.2    35.6                78.6               5.9
 8 Delaware              984  25.7    36.9                80.1               8.7
 9 District of Columb…   987  25.6    36.3                NA                NA  
10 Florida               993  20.4    39.3                78.4               8.9
# ℹ 41 more rows
# ℹ 1 more variable: Binge_Drinkers &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="data-limitations" class="level3">
<h3 class="anchored" data-anchor-id="data-limitations">Data Limitations</h3>
<p>One of the more pertinent limitations to this data is the fact that not every high school student takes standardized tests such as the ACT and SAT. These tests are usually taken by students who intend to pursue higher education (college). They are not mandatory, and not every high schoolers takes them. Therefore, whatever conclusions drawn from this data cannot be applied to high schoolers as a whole - only this specific group of high schoolers.</p>
<p>Additionally, the YRBSS data possesses is incomplete - it is missing data for a few different states. This can be worked around reasonably via data imputation, however, it is still a potential issue worth noting.</p>
<p>Finally, the survey-based data collection of the YRBSS (as described here: [[https://www.cdc.gov/yrbs/methods/index.html]]) means that biases may appear in its data collection. For example, some of the students surveyed may have responded dishonestly. On top of this, observational studies such as these surveys cannot prove causation. Even if some connection between test scores is seen within the data, it will not prove that one is caused by the other. Perhaps lowered test scores cause depression, perhaps a worsened mood causes a lack of motivation and lower test scores, or perhaps some combination of these is true - however, this analysis cannot determinen which of these is true.</p>
</section>
</section>
<section id="data-wrangling-optional-section" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling-optional-section">Data Wrangling (Optional Section)</h2>
<p>As mentioned above, there are several states that have missing data for various different statistics. I will make use of linear model imputation in order to do this. Linear imputation is appropriate here, since this data appears to be a case missing completely at random - there is no pattern among the states with missing data or commonality that they all share. The data is most likely missing due to surveyors not being particularly active in these states or some other fluke, rather than because of the impact of the variable of mental health itself (excluding the possibility of the missing data from being missing at random or not missing at random).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data2021imputed <span class="ot">&lt;-</span> <span class="fu">recipe</span>(ACT <span class="sc">~</span> Sadness <span class="sc">+</span> Not_Sleeping_Enough <span class="sc">+</span> Attempted_Suicide <span class="sc">+</span> Binge_Drinkers,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> data2021) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_linear</span>(<span class="fu">c</span>(Sadness, Not_Sleeping_Enough, Attempted_Suicide, Binge_Drinkers), <span class="at">impute_with =</span> <span class="fu">imp_vars</span>(ACT))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>data2021_full <span class="ot">&lt;-</span> data2021imputed <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prep</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bake</span>(<span class="at">new_data =</span> <span class="cn">NULL</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>data2021_full</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51 × 5
   Sadness Not_Sleeping_Enough Attempted_Suicide Binge_Drinkers   ACT
     &lt;dbl&gt;               &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt; &lt;dbl&gt;
 1    36.9                77.4             11.2            36.9  18.7
 2    40.6                77.3             10.8            40.6  20.6
 3    40.8                79.3             10.4            40.8  19.8
 4    42.9                77.8             10.4            42.9  19  
 5    38.7                78.2              9.59           38.7  26.1
 6    41.7                75.6             11.9            41.7  23.6
 7    35.6                78.6              5.9            35.6  27.2
 8    36.9                80.1              8.7            36.9  25.7
 9    36.3                78.1              9.69           36.3  25.6
10    39.3                78.4              8.9            39.3  20.4
# ℹ 41 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data2021_final <span class="ot">&lt;-</span> <span class="fu">cbind</span>(data2021[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], data2021_full[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data2021_final</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  State  SAT  ACT  Sadness Not_Sleeping_Enough
1               Alabama 1159 18.7 36.90000            77.40000
2                Alaska 1119 20.6 40.55472            77.32535
3               Arizona 1181 19.8 40.82899            79.30000
4              Arkansas 1194 19.0 42.90000            77.80000
5            California 1057 26.1 38.66910            78.18081
6              Colorado 1072 23.6 41.70000            75.60000
7           Connecticut 1072 27.2 35.60000            78.60000
8              Delaware  984 25.7 36.90000            80.10000
9  District of Columbia  987 25.6 36.30000            78.10304
10              Florida  993 20.4 39.30000            78.40000
11              Georgia 1086 22.6 43.50000            75.60000
12               Hawaii 1144 18.2 34.80000            76.50000
13                Idaho  985 23.0 44.80000            77.69864
14             Illinois 1007 25.2 42.10000            80.60000
15              Indiana 1095 23.1 46.90000            82.10000
16                 Iowa 1243 21.5 39.10000            72.60000
17               Kansas 1243 19.9 37.70000            74.40000
18             Kentucky 1219 19.2 39.20000            80.00000
19            Louisiana 1188 18.4 47.50000            80.30000
20                Maine 1099 25.6 37.90000            78.10304
21             Maryland 1073 25.5 39.20000            78.08749
22        Massachusetts 1184 27.6 38.50000            79.60000
23             Michigan 1031 25.1 40.30000            81.20000
24            Minnesota 1263 21.6 40.21188            77.48089
25          Mississippi 1202 18.1 41.80000            76.70000
26             Missouri 1219 20.6 32.50000            78.00000
27              Montana 1225 20.4 41.40000            71.40000
28             Nebraska 1246 20.0 36.40000            73.50000
29               Nevada 1195 17.8 45.60000            79.50000
30        New Hampshire 1065 26.6 44.20000            76.70000
31           New Jersey 1125 25.1 41.50000            77.40000
32           New Mexico  996 20.7 42.50000            71.40000
33             New York 1057 26.3 31.40000            77.30000
34       North Carolina 1150 18.9 43.40000            81.80000
35         North Dakota 1258 19.6 36.00000            75.50000
36                 Ohio 1048 19.6 42.60000            81.00000
37             Oklahoma 1042 19.7 43.50000            79.20000
38               Oregon 1119 20.6 40.55472            77.32535
39         Pennsylvania 1123 25.0 43.70000            83.90000
40         Rhode Island 1011 25.8 37.80000            76.40000
41       South Carolina 1036 18.6 41.10000            76.30000
42         South Dakota 1215 21.6 38.70000            71.30000
43            Tennessee 1220 19.1 42.20000            79.50000
44                Texas 1003 20.1 44.60000            75.60000
45                 Utah 1238 20.6 41.50000            76.50000
46              Vermont 1124 24.7 29.60000            77.96306
47             Virginia 1151 25.5 38.20000            76.00000
48           Washington 1072 23.6 39.52620            77.79197
49        West Virginia 1007 20.8 47.50000            82.50000
50            Wisconsin 1215 20.0 33.70000            72.00000
51              Wyoming 1233 19.8 40.82899            77.20092
   Attempted_Suicide Binge_Drinkers
1          11.190535       36.90000
2          10.778572       40.55472
3          10.400000       40.82899
4          10.400000       42.90000
5           9.586047       38.66910
6          11.900000       41.70000
7           5.900000       35.60000
8           8.700000       36.90000
9           9.694458       36.30000
10          8.900000       39.30000
11         15.600000       43.50000
12          7.400000       34.80000
13         10.900000       44.80000
14          8.400000       42.10000
15         11.800000       46.90000
16         10.200000       39.10000
17         16.100000       37.70000
18          9.500000       39.20000
19         17.600000       47.50000
20          9.600000       37.90000
21         17.300000       39.20000
22          7.600000       38.50000
23          9.000000       40.30000
24         10.561749       40.21188
25         16.200000       41.80000
26          8.700000       32.50000
27         10.200000       41.40000
28         10.100000       36.40000
29         12.200000       45.60000
30          9.800000       44.20000
31          9.500000       41.50000
32         10.100000       42.50000
33          9.200000       31.40000
34         10.100000       43.40000
35          6.100000       36.00000
36          9.500000       42.60000
37          9.900000       43.50000
38          9.500000       40.55472
39          9.700000       43.70000
40          9.651094       37.80000
41         11.900000       41.10000
42         13.400000       38.70000
43         12.300000       42.20000
44          9.000000       44.60000
45          6.900000       41.50000
46          9.000000       29.60000
47          9.716140       38.20000
48         12.100000       39.52620
49          8.500000       47.50000
50         10.908666       33.70000
51         10.952030       40.82899</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>We will examine the the distributions of the data in this EDA. Beginning with test scores, we have the SAT and ACT:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data2021_final,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> SAT)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/Test score distributions-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data2021_final,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> ACT)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/Test score distributions-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>An initial overview of the distributions of SAT and ACT scores does not reveal any extreme outliers or unusual data points. Both distributions are somewhat irregular - they are not normal, uniform, or otherwise following a commonly distribution. Additionally, both data sets have multiple “peaks” (modes). The ACT notably appears to have two nodes, one at 20.0 and another at 25.0.</p>
<p>We will now examine the imputed data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data2021_final,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Sadness)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data2021_final,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Not_Sleeping_Enough)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data2021_final,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Attempted_Suicide)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data2021_final,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Binge_Drinkers)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interestingly, all of the distributions for each of the four critera appear to be fairly close to normal, in spite of their differing centers. They also appear to have roughly similar rangers, except for “Attempted_Suicide”, which is slightly lower.</p>
</section>
<section id="modeling" class="level2">
<h2 class="anchored" data-anchor-id="modeling">Modeling</h2>
<p>It is natural to assume that an inverse relationship exists between test scores and the various selected indicators for mental health. That is, an increase in test scores should precipiate a decrease in the percentage of people suffering from various indications of mental health issues.</p>
<p>Due to this, I will test whether a linear relationship between test scores and these mental health indicators. I am doing this under the assumption that worsening mental health causes worse test scores at a linear rate - a drop in mental health will result in a drop in academic performance, regardless of whether you were originally perfectly fine or in the throes of depression. I will create a model for both the SAT and the ACT model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">437</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sample_index <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="dv">51</span>), <span class="at">size =</span> <span class="dv">41</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>train_data2021 <span class="ot">&lt;-</span> data2021_final[sample_index,]</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>test_data2021 <span class="ot">&lt;-</span> data2021_final[<span class="sc">-</span>sample_index,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>SAT_linearmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(SAT <span class="sc">~</span> Sadness <span class="sc">+</span> Not_Sleeping_Enough <span class="sc">+</span> Attempted_Suicide <span class="sc">+</span> Binge_Drinkers, <span class="at">data =</span> train_data2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ACT_linearmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(ACT <span class="sc">~</span> Sadness <span class="sc">+</span> Not_Sleeping_Enough <span class="sc">+</span> Attempted_Suicide <span class="sc">+</span> Binge_Drinkers, <span class="at">data =</span> train_data2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To evaluate the accuracy of these linear models, a measure of root-mean squared error (RMSE) will be taken for each model.</p>
</section>
<section id="insights" class="level2">
<h2 class="anchored" data-anchor-id="insights">Insights</h2>
<p>An cursory examination of the summaries for both of the linear models shows the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SAT_linearmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SAT ~ Sadness + Not_Sleeping_Enough + Attempted_Suicide + 
    Binge_Drinkers, data = train_data2021)

Residuals:
     Min       1Q   Median       3Q      Max 
-158.252  -64.977    1.019   66.602  146.893 

Coefficients: (1 not defined because of singularities)
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         1778.563    370.873   4.796 2.65e-05 ***
Sadness               -3.065      4.419  -0.694    0.492    
Not_Sleeping_Enough   -8.014      5.010  -1.600    0.118    
Attempted_Suicide      7.740      5.543   1.396    0.171    
Binge_Drinkers            NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 86.66 on 37 degrees of freedom
Multiple R-squared:  0.1663,    Adjusted R-squared:  0.09871 
F-statistic:  2.46 on 3 and 37 DF,  p-value: 0.07792</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ACT_linearmodel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ACT ~ Sadness + Not_Sleeping_Enough + Attempted_Suicide + 
    Binge_Drinkers, data = train_data2021)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.6259 -2.2797  0.2427  1.9028  5.5515 

Coefficients: (1 not defined because of singularities)
                    Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)          12.5766    10.6342   1.183   0.2445  
Sadness              -0.3280     0.1267  -2.589   0.0137 *
Not_Sleeping_Enough   0.3259     0.1437   2.268   0.0292 *
Attempted_Suicide    -0.2064     0.1589  -1.299   0.2021  
Binge_Drinkers            NA         NA      NA       NA  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.485 on 37 degrees of freedom
Multiple R-squared:  0.2802,    Adjusted R-squared:  0.2218 
F-statistic: 4.801 on 3 and 37 DF,  p-value: 0.006357</code></pre>
</div>
</div>
<p>In both cases, the <span class="math inline">\(R^2\)</span> value is very low (0.166 for SAT, 0.2802 for ACT). This further demonstrates that a linear model is inadequate for describing the relationship between test scores and the selected mental health indicators.</p>
<section id="limitations-and-future-work" class="level3">
<h3 class="anchored" data-anchor-id="limitations-and-future-work">Limitations and Future Work</h3>
<p>One of the limitations that may be at play here is in the stanardized test scores. Here is a graph of the data I found showing the SAT scores vs.&nbsp;the ACT scores. Each dot represents one of the fifty states (and the District of Columbia) during the year of 2021:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data2021_final, <span class="fu">aes</span>(<span class="at">x =</span> SAT, <span class="at">y =</span> ACT)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Bizarrely, there appears to be no relationship between the two sets of test scores at all - in fact, the (highly inaccurate) line of best fit claims that there is an inverse relationship between the two variables! This is highly counterintuitive, as one would expect these scores to be directly correlated - an increase in one ought to see an increase in the other, as better students perform better on tests in general. This leads me to suspect that either one or both of the test score data sets is inaccurate, or that each survey examined a different part of each state’s population such that there was little to no overlap. Either way, the above result may be partly causing the lack of any meaningful correlation between the examined variables. If I were to do this again, I would make absolutely certain that the test score data was being drawn from as reliable of a source as possible.</p>
<p>Additionally, in this analysis I have made some assumptions that a deteriorating mental health has a simple, straightforward relationship (linear) that can be represented using common methods. This is, of course, a very big assumption. The human mind’s relationship with these test scores may not follow any logical relationship at all.</p>
</section>
<section id="reflection-optional-subsection" class="level3">
<h3 class="anchored" data-anchor-id="reflection-optional-subsection">Reflection (Optional Subsection)</h3>
<p>(Reflection included in Canvas submission)</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Made with ❤️ and Quarto</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>