project:
  type: website

website:
  title: "Aaron Kim"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - FinalProject.qmd
      
format:
  html:
    backgroundcolor: "#eeffee"
    fontcolor: "darkgreen"
    mainfont: "monospace"
    theme: [cosmo, styles.scss]

